### ISSUE TITLE
Two fonts in wrong directory?

### ISSUE THREAD

**Issue by BPickle** [notofonts/duployan#8]
NotoSansDuployan/hinted/otf/NotoSansDuployan-Bold.otf
NotoSansDuployan/hinted/otf/NotoSansDuployan-Regular.otf

Shouldn't these two fonts be in a /full/otf/ folder? I think these may be the only two OTF fonts that are in a hinted folder instead of a full folder.

**Comment by mi2ebi** [comment]
shouldn't there also be s full/ttf ?

**Comment by BPickle** [comment]
Maybe there should be a full/ttf directory too. But this was the only instance I found where fonts were in a spot that for sure seemed incorrect.

There were also directories that seemed duplicative, such as /full/variable/ and /full/variable-ttf/, and /unhinted/variable/and /unhinted/variable-ttf/.

**Comment by simoncozens** [comment]
Because of the way the Duployan fonts are created - which is *way* different from the standard build process; they don't have UFO or Glyphs sources - we do not provide full (i.e. including a Latin) builds of these fonts. So no, they should not be in a `full` directory.  If you really want a "full" build, the `googlefonts` directory contains versions with a merged Latin.

**Comment by BPickle** [comment]
My apologies for not noticing that the fonts in question did not include Latin characters.
